// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzbnjOKdt6hOQb_xj-P2grumByaYn-JeQ',
    appId: '1:559342509154:web:614c9516cf3640d73c053b',
    messagingSenderId: '559342509154',
    projectId: 'buku-kontak-fahri',
    authDomain: 'buku-kontak-fahri.firebaseapp.com',
    storageBucket: 'buku-kontak-fahri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1XtUc08sZc1zyoy83cHYhwDBBUWfSsY',
    appId: '1:559342509154:android:fabf762a596444b33c053b',
    messagingSenderId: '559342509154',
    projectId: 'buku-kontak-fahri',
    storageBucket: 'buku-kontak-fahri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClczVwnKuc7Z3b1_CIFPa-q48mFFUGAbw',
    appId: '1:559342509154:ios:50dd40812029c0513c053b',
    messagingSenderId: '559342509154',
    projectId: 'buku-kontak-fahri',
    storageBucket: 'buku-kontak-fahri.firebasestorage.app',
    iosBundleId: 'com.example.kontakForm',
  );
}
